# Site settings
title: gsa home
description: "gsa home"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: gsa home
user_title: Lorem Ipsum - FrontEnd
email: gurbirwalia@gmail.com
twitter_username: 
github_username:  
gplus_username:  
linkedin_public_url:  # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: 
profile_picture: http://pm1.narvii.com/6760/603059bb41250b8acaa078e07246d8bf84ae02efv2_00.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: blueiris
      url: http://sec.gsa.ink:10069/
      key_trigger: 1
    - title: esxi
      url: http://esxi.gsa.ink
      key_trigger: 2
    - title: unifi
      url: https://unifi.gsa.ink:8443/
      key_trigger: 3

# projects in header index
#projects:
#  - name: esxi
#    url: https://esxi.gsa.ink
#  - name: vim-frontend
#    url: https://github.com/victorvoid/vim-frontend
#  - name: generator-capybara
#    url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
